/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SLOT_CLK.h"
#include "CREG_PAY.h"
#include "SHIFT_CLK.h"
#include "SREG_HAM_OUT.h"
#include "DMA_HAM2SER_dma.h"
#include "CREG_SER.h"
#include "SREG_SYMB.h"
#include "DMA_PAY_dma.h"
#include "CREG_L.h"
#include "ISR_SYMB.h"
#include "ISR_INJ_CHECK.h"
#include "UART.h"
#include "CREG_INJ_DONE.h"
#include "PWM_LED.h"
#include "CREG_INIT_TX.h"
#include "Pin_1_aliases.h"
#include "Pin_1.h"
#include "CREG_RX_SLOTS1.h"
#include "CREG_RX_SLOTS2.h"
#include "SREG_HEAD.h"
#include "COMP_SLOW.h"
#include "COMP_FAST.h"
#include "DAC_SLOW.h"
#include "DAC_FAST.h"
#include "Pin_2_aliases.h"
#include "Pin_2.h"
#include "Pin_3_aliases.h"
#include "Pin_3.h"
#include "Pin_4_aliases.h"
#include "Pin_4.h"
#include "Pin_5_aliases.h"
#include "Pin_5.h"
#include "ADC_SAR.h"
#include "DMA_AVG_dma.h"
#include "ISR_HEADER_READ.h"
#include "DMA_RX_dma.h"
#include "ISR_ADC_RX.h"
#include "UART_IntClock.h"
#include "DAC_SLOW_DMA_dma.h"
#include "DAC_SLOW_VDAC8.h"
#include "DAC_SLOW_IntClock.h"
#include "DAC_FAST_DMA_dma.h"
#include "DAC_FAST_VDAC8.h"
#include "DAC_FAST_IntClock.h"
#include "ADC_SAR_IRQ.h"
#include "ADC_SAR_theACLK.h"
#include "ADC_SAR_Bypass_aliases.h"
#include "ADC_SAR_Bypass.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

