/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "DEB_PIN1_aliases.h"
#include "DEB_PIN1.h"
#include "DEB_PIN0_aliases.h"
#include "DEB_PIN0.h"
#include "CREG_PAY_SIZE.h"
#include "ISR_SYMB_1.h"
#include "LED_OUT_aliases.h"
#include "LED_OUT.h"
#include "PWM_LED_1.h"
#include "DMA_PAY_dma.h"
#include "CREG_TX_INIT.h"
#include "UART.h"
#include "SHIFT_CLK.h"
#include "SLOT_CLK.h"
#include "DEB_PIN2_aliases.h"
#include "DEB_PIN2.h"
#include "DEB_PIN3_aliases.h"
#include "DEB_PIN3.h"
#include "DEB_PIN4_aliases.h"
#include "DEB_PIN4.h"
#include "CREG_PAY.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

